# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "cFrueeZnhU3vFCfMyuH8Lvc9GIOlJknsYlV1/mz69XzybI2L4xWe+E62bXIU3mUoMYBh4q91HnRgnGnwpfq9IAYIg2GzFa6Pircxn4Weg5ryO+ClJWEJQWN7dXb4TWk/Er4IiLvUSrNprJb6SNeTi/jsDS9A50oRZpxQ+6KJDgoenWZxQ0eZacyOpPtQylIpBSg9gEJuwy7JiBR+gHyE/LEBlzCRUWdtIZIDQX2hgxC/2MNlUq6SInwWTLmoZy1Eyz4KzsoMidJXVPdzbXFV2cX0i4vALqxGJUvPoVyTpQ9y2dM1+fPCho+LltYGDj1pMG/ROK+MmYky2M3yVPB0iBHda+ARy5Shtihm4EGrnqjd5sSeGfmUT7b4MZhZxHkrR3nGlOPYwFSteTbtuTsqDKO2QCMIYszzJ6VtXNi+Rqv+2HmAeZRxHYTh/y9mjJby0DWD0U5r5mbO8ZSz6LYengKGFsonXcpPLLlyJ3sB4AkIr32ivMMJ87RTRWlfQKeW8dG01mj6HM2rIf18wIK32/+kuGG6nzA8B/VYQeSnMo4P4SLnzZkQ4IMR8sbZUM2PUitBBax9sKbqjiMTszPAatjxXFIeB2Rb04FiAGoNozukpaCh0rBPbHJBjhY/3xgy/9vxE3zeiZoEOa5++7aEbDt63ndHuMfgneP0+fHfYtE="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
