appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: K8OLHQjovEp1F33ZzOcwgzn7/QJ4BXWa37BIz7zhTI0jaG553uuAYwqf4c7UfHN/tfKZOCbnaiZ4ZUi7Pn3E2FvGtQaDDqqJVRvqWkHd/9VXjEYKzLdCv9mLYbpHjyZgjgrzL5CyMC9jRUHcPQF1x78cc/nYMlYJoBimvBqH4wbOabO2AG4kaWK1hKof2M9QxiYeIJl8Fkg9wJVX1rfyjCdcCrakkoomqLohyB3jxq2a3r6nZStVBPlOlEuRwWH0rWqidRFluEPDwTXRWJ7/WrqRUqN4M6z6PNcABNIt+OyVCkD0wgCFcfRPccXLCTCpitJzr68EuUAoMDIytWMAuzQIn1DZLW/rNCJq3zEaFeEhRUpSZC0UDsmciCo1RLSN/t4p7zVOAV4Ty2PkGaMv867JP3NRjoQ/mCKSJ84zlnWO/QNlyo89yZGygaA1ZRJX7CHs303jNa93NmMM+yEn0z6+dKdmy1D6RurLlxNDOAUre5prpIw7IrYh80c9FQ/sGealdh1s2j5TXipatOMcoTybRVGn3H+ujUr0V6e/a9hGwbSd9d6Yeq4GyAZKUz1hfYDddQ0CpiFCPxo8w10vkCdVvvMpQfVl2MW2MsMEbq57nELy5nFbunn/Er6V2A4lFenYa9y1eJ36SfJxqarH9fLueuGgP/sqOjBTp6KEs/0=}
