travis:
  secure:
    BINSTAR_TOKEN: cFrueeZnhU3vFCfMyuH8Lvc9GIOlJknsYlV1/mz69XzybI2L4xWe+E62bXIU3mUoMYBh4q91HnRgnGnwpfq9IAYIg2GzFa6Pircxn4Weg5ryO+ClJWEJQWN7dXb4TWk/Er4IiLvUSrNprJb6SNeTi/jsDS9A50oRZpxQ+6KJDgoenWZxQ0eZacyOpPtQylIpBSg9gEJuwy7JiBR+gHyE/LEBlzCRUWdtIZIDQX2hgxC/2MNlUq6SInwWTLmoZy1Eyz4KzsoMidJXVPdzbXFV2cX0i4vALqxGJUvPoVyTpQ9y2dM1+fPCho+LltYGDj1pMG/ROK+MmYky2M3yVPB0iBHda+ARy5Shtihm4EGrnqjd5sSeGfmUT7b4MZhZxHkrR3nGlOPYwFSteTbtuTsqDKO2QCMIYszzJ6VtXNi+Rqv+2HmAeZRxHYTh/y9mjJby0DWD0U5r5mbO8ZSz6LYengKGFsonXcpPLLlyJ3sB4AkIr32ivMMJ87RTRWlfQKeW8dG01mj6HM2rIf18wIK32/+kuGG6nzA8B/VYQeSnMo4P4SLnzZkQ4IMR8sbZUM2PUitBBax9sKbqjiMTszPAatjxXFIeB2Rb04FiAGoNozukpaCh0rBPbHJBjhY/3xgy/9vxE3zeiZoEOa5++7aEbDt63ndHuMfgneP0+fHfYtE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
